class_name IconesDesenhados
## Ícones desenhados em pixel art (16×16, ampliados 3×) para o que não tem modelo 3D para
## fotografar: as ferramentas do editor, o início do cachorro, as zonas, a parede invisível e os
## módulos. Cada ícone é um desenho em letras (uma letra = uma cor, "." = transparente), como os
## modelos voxel em texto.

const ESCALA := 3

const CORES := {
	"k": Color("1b1b22"), "w": Color("f4f4f0"), "g": Color("9aa0a8"), "d": Color("5c6068"),
	"y": Color("f2c94c"), "o": Color("f2994a"), "r": Color("e0564a"), "b": Color("4a90e2"),
	"c": Color("7fd4ff"), "v": Color("6cc24a"), "m": Color("8a5a34"), "p": Color("f07fb4"),
}

const DESENHOS := {
	"cursor": [
		"..k.............",
		"..kk............",
		"..kwk...........",
		"..kwwk..........",
		"..kwwwk.........",
		"..kwwwwk........",
		"..kwwwwwk.......",
		"..kwwwwwwk......",
		"..kwwwwwwwk.....",
		"..kwwwwwkkkk....",
		"..kwwkwwk.......",
		"..kwk.kwwk......",
		"..kk..kwwk......",
		"..k....kwwk.....",
		".......kwwk.....",
		"........kk......",
	],
	"trecho": [
		"................",
		".yy.yy.yy.yy.yy.",
		".y.............y",
		"................",
		".y.............y",
		".y..gggggggg...y",
		"....gvvvvvvg....",
		".y..gvvvvvvg...y",
		".y..gmmmmmmg...y",
		"....gmmmmmmg....",
		".y..gggggggg...y",
		".y.............y",
		"................",
		".y.............y",
		".yy.yy.yy.yy.yy.",
		"................",
	],
	"ligar": [
		"................",
		"................",
		".bbbb...........",
		"bwwwwb..........",
		"bw..wb..........",
		"bw..wbbbb.......",
		"bwwwwbwwwb......",
		".bbbbw..wb......",
		".....bw..wbbbb..",
		".....bwwwwbwwwb.",
		"......bbbbw..wb.",
		"..........bw..wb",
		"..........bwwwwb",
		"...........bbbb.",
		"................",
		"................",
	],
	"pincel": [
		"................",
		"...........kk...",
		"..........kmmk..",
		".........kmmk...",
		"........kmmk....",
		".......kmmk.....",
		"......kmmk......",
		".....kggk.......",
		"....kvvgk.......",
		"...kvvvk........",
		"..kvvvk.........",
		"..kvvk..........",
		".kvvk...........",
		".kkk............",
		"................",
		"................",
	],
	"trocar": [
		"................",
		"....yyyyyy......",
		"...y......y.....",
		"..y........y.y..",
		"..y.........yy..",
		"..y........yyy..",
		"................",
		"...vvvv..mmmm...",
		"...vvvv..mmmm...",
		"...vvvv..mmmm...",
		"................",
		"..yyy........y..",
		"..yy.........y..",
		"..y.y........y..",
		".....y......y...",
		"......yyyyyy....",
	],
	"linha": [
		"................",
		"................",
		".............vv.",
		"............vvv.",
		"...........vvv..",
		"..........vvv...",
		".........vvv....",
		"........vvv.....",
		".......vvv......",
		"......vvv.......",
		".....vvv........",
		"....vvv.........",
		"...vvv..........",
		"..vvv...........",
		"..vv............",
		"................",
	],
	"retangulo": [
		"................",
		"................",
		".kkkkkkkkkkkkkk.",
		".kvvvvvvvvvvvvk.",
		".kvvvvvvvvvvvvk.",
		".kvvvvvvvvvvvvk.",
		".kvvvvvvvvvvvvk.",
		".kmmmmmmmmmmmmk.",
		".kmmmmmmmmmmmmk.",
		".kmmmmmmmmmmmmk.",
		".kmmmmmmmmmmmmk.",
		".kkkkkkkkkkkkkk.",
		"................",
		"................",
		"................",
		"................",
	],
	"balde": [
		"................",
		"......kkkk......",
		".....k....k.....",
		"....k......k....",
		"...kggggggggk...",
		"...kgwggggggk.b.",
		"...kgwggggggkbb.",
		"....kgggggggkbb.",
		"....kgggggggk.b.",
		"....kgggggggk...",
		".....kgggggk....",
		".....kkkkkkk....",
		"................",
		"...bbbbbbbbbb...",
		"..bbbbbbbbbbbb..",
		"................",
	],
	"modulo": [
		"................",
		".kkkkkkk.kkkkkk.",
		".kvvvvvk.kvvvvk.",
		".kvvvvvk.kvvvvk.",
		".kmmmmmk.kmmmmk.",
		".kmmmmmk.kmmmmk.",
		".kkkkkkk.kkkkkk.",
		"................",
		".kkkkkk.kkkkkkk.",
		".kbbbbk.kvvvvvk.",
		".kbbbbk.kvvvvvk.",
		".kbbbbk.kmmmmmk.",
		".kmmmmk.kmmmmmk.",
		".kkkkkk.kkkkkkk.",
		"................",
		"................",
	],
	"inicio": [
		"................",
		"....oo....oo....",
		"...oooo..oooo...",
		"...oooo..oooo...",
		"....oo....oo....",
		".oo..........oo.",
		"oooo........oooo",
		"oooo........oooo",
		".oo...oooo...oo.",
		".....oooooo.....",
		"....oooooooo....",
		"....oooooooo....",
		"....oooooooo....",
		".....oooooo.....",
		"................",
		"................",
	],
	"parede": [
		"................",
		".cccccccccccccc.",
		".c.c.c.c.c.c.cc.",
		".cc.c.c.c.c.c.c.",
		".c.c.c.c.c.c.cc.",
		".cc.c.c.c.c.c.c.",
		".c.c.c.c.c.c.cc.",
		".cc.c.c.c.c.c.c.",
		".c.c.c.c.c.c.cc.",
		".cc.c.c.c.c.c.c.",
		".c.c.c.c.c.c.cc.",
		".cc.c.c.c.c.c.c.",
		".c.c.c.c.c.c.cc.",
		".cccccccccccccc.",
		"................",
		"................",
	],
	"sem_largar": [
		"................",
		".....rrrrrr.....",
		"...rr......rr...",
		"..r.........rr..",
		".r.........r..r.",
		".r........r...r.",
		"r...mmmmmr.....r",
		"r...mmmmr......r",
		"r......r.......r",
		"r.....r........r",
		".r...r........r.",
		".r..r.........r.",
		"..rr.........r..",
		"...rr......rr...",
		".....rrrrrr.....",
		"................",
	],
	"dica": [
		"................",
		"..kkkkkkkkkkkk..",
		".kwwwwwwwwwwwwk.",
		".kwwwwwyywwwwwk.",
		".kwwwwwyywwwwwk.",
		".kwwwwwyywwwwwk.",
		".kwwwwwyywwwwwk.",
		".kwwwwwwwwwwwwk.",
		".kwwwwwyywwwwwk.",
		".kwwwwwwwwwwwwk.",
		"..kkkkwkkkkkkk..",
		"......kwk.......",
		".......kk.......",
		"................",
		"................",
		"................",
	],
}

static var _cache := {}


static func existe(nome: String) -> bool:
	return DESENHOS.has(nome)


## O ícone `nome` (ou null se não existir).
static func textura(nome: String) -> Texture2D:
	if not DESENHOS.has(nome):
		return null
	if not _cache.has(nome):
		var linhas: Array = DESENHOS[nome]
		var imagem := Image.create(16 * ESCALA, 16 * ESCALA, false, Image.FORMAT_RGBA8)
		imagem.fill(Color(0, 0, 0, 0))
		for y in linhas.size():
			var linha: String = linhas[y]
			for x in mini(linha.length(), 16):
				var letra := linha[x]
				if CORES.has(letra):
					imagem.fill_rect(Rect2i(x * ESCALA, y * ESCALA, ESCALA, ESCALA), CORES[letra])
		_cache[nome] = ImageTexture.create_from_image(imagem)
	return _cache[nome]
